package br.edu.ifpr.messages.views;


import br.edu.ifpr.messages.DAOs.MessageDAO;
import br.edu.ifpr.messages.DAOs.UserDAO;
import br.edu.ifpr.messages.entities.Message;
import br.edu.ifpr.messages.entities.User;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joao
 */
public class CreateMessage extends javax.swing.JFrame {

    /**
     * Creates new form CadastroMensagem
     */
    public CreateMessage() {
        initComponents();
        this.preencherListaDeUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMensagem = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnListaDeMensagens = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listUsuarios = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnviar.setText("Enviar mensagem");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnListaDeMensagens.setText("Visualizar mensagens");
        btnListaDeMensagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaDeMensagensActionPerformed(evt);
            }
        });

        jLabel1.setText("Envio de mensagens");

        jLabel2.setText("Selecione o contato");

        listUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listUsuariosActionPerformed(evt);
            }
        });

        btnLogin.setText("Logout");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnLogin)
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnListaDeMensagens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btnLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListaDeMensagens)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        User remetente = l.usuarioLogado();
        
        String username_destinatario = (String) this.listUsuarios.getSelectedItem();
        
        User destinatario = this.procurarPorUsername(username_destinatario);
       
        String corpo = txtMensagem.getText().trim();

        Message message = new Message(corpo, remetente.getId(), destinatario.getId());
        
        MessageDAO dao = new MessageDAO();
        
        try {
            dao.inserir(message);

            JOptionPane.showMessageDialog(this, "Mensagem enviada!");

            this.limparCampos();
        } catch (SQLException ex) {
            Logger.getLogger(CreateMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        this.dispose();
        l.setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnListaDeMensagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaDeMensagensActionPerformed
        // TODO add your handling code here:
        ListaDeMensagensRecebidas lm = null;
        try {
            lm = new ListaDeMensagensRecebidas();
        } catch (SQLException ex) {
            Logger.getLogger(CreateMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        lm.setVisible(true);
    }//GEN-LAST:event_btnListaDeMensagensActionPerformed

    private void listUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listUsuariosActionPerformed

    public void preencherListaDeUsuarios() {
        UserDAO dao = new UserDAO();
        
        ArrayList<User> usuarios = new ArrayList();
        
        try {

            Login l = new Login();
            User usuarioLogado = l.usuarioLogado();

            usuarios = dao.selecionarTodos(usuarioLogado.getId());
        } catch (SQLException ex) {
            Logger.getLogger(CreateMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(User u: usuarios) {
            this.listUsuarios.addItem(u.getUsername());
        }
    }
    
    public User procurarPorUsername(String username) {
        UserDAO dao = new UserDAO();
        
        ArrayList<User> usuarios = new ArrayList();
        
        try {
            Login l = new Login();
            User usuarioLogado = l.usuarioLogado();

            usuarios = dao.selecionarTodos(usuarioLogado.getId());
        } catch (SQLException ex) {
            Logger.getLogger(CreateMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        User destinatario = new User();
        
        for(User u: usuarios) {
            if(u.getUsername().equals(username)) {
                destinatario = u;
            }
        }
        
        return destinatario;
    }
    
    public void limparCampos() {
        txtMensagem.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnListaDeMensagens;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> listUsuarios;
    private javax.swing.JTextField txtMensagem;
    // End of variables declaration//GEN-END:variables

}
