/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.views;

import br.edu.ifpr.DAOs.CategoryDAO;
import br.edu.ifpr.entities.Category;
import br.edu.ifpr.entities.Transaction;
import br.edu.ifpr.models.TransactionsModel;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alunoadm
 */
public class CreateTransactionView extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public CreateTransactionView() {
        initComponents();
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonTypeGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameInputText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        priceInputText = new javax.swing.JTextField();
        buttonIncome = new javax.swing.JRadioButton();
        buttonOutcome = new javax.swing.JRadioButton();
        CategoriesBox = new javax.swing.JComboBox();
        submitButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateInputText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nome");

        jLabel2.setText("Preço");

        buttonTypeGroup.add(buttonIncome);
        buttonIncome.setForeground(new java.awt.Color(0, 255, 51));
        buttonIncome.setText("Entrada");
        buttonIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIncomeActionPerformed(evt);
            }
        });

        buttonTypeGroup.add(buttonOutcome);
        buttonOutcome.setForeground(new java.awt.Color(255, 0, 0));
        buttonOutcome.setText("Saida");
        buttonOutcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutcomeActionPerformed(evt);
            }
        });

        CategoriesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriesBoxActionPerformed(evt);
            }
        });

        submitButton.setText("Enviar");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel3.setText("Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nameInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonIncome)
                                .addGap(18, 18, 18)
                                .addComponent(buttonOutcome))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(CategoriesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonIncome)
                    .addComponent(buttonOutcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CategoriesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(submitButton)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initData() {
        try {
            ArrayList<Category> categories = this.getCategories();
         
            for (Category category: categories) {
                this.CategoriesBox.addItem(category.getName());
            }
        } catch (Exception e) {
            Logger.getLogger(CreateTransactionView.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    private ArrayList<Category> getCategories() {
        CategoryDAO categoriesDAO = new CategoryDAO();

        try {
            ArrayList<Category> categories = categoriesDAO.list();
         
            if (categories.isEmpty() == false) return categories;

            categoriesDAO.seed();
            categories = categoriesDAO.list();

            return categories;
        } catch (SQLException e) {
            Logger.getLogger(CreateTransactionView.class.getName()).log(Level.SEVERE, null, e);
        }
        return null;
    }

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Home view = new Home();
        view.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void CategoriesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriesBoxActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String name = nameInputText.getText();
        float price = Float.parseFloat(priceInputText.getText());
        String selectedType = this.getSelectedButton();
        String selectedCategory = CategoriesBox.getSelectedItem().toString();
        String dateString = dateInputText.getText();

        Date date = this.stringToDate(dateString);

        if (date == null) return;

        Transaction transaction = new Transaction(
            name, 
            price, 
            date, 
            selectedType, 
            selectedCategory,
            Login.currentUser.getId()
        );

        TransactionsModel transactionsModel = new TransactionsModel();
 
        transactionsModel.create(transaction);

        JOptionPane.showMessageDialog(
            this,
            "Transação criada com sucesso!",
            "Sucesso",
            JOptionPane.INFORMATION_MESSAGE
        );

        this.cleanFields();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cleanFields() {
        nameInputText.setText("");
        priceInputText.setText("");
        dateInputText.setText("");
    }

    private Date stringToDate(String dateString) {
        try {
            Date date = new SimpleDateFormat("dd/MM/yyyy").parse(dateString);

            return date;
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(
                this,
                "Data inválida! Digite no formato dd/mm/AAAA",
                "Error!",
                JOptionPane.ERROR_MESSAGE
            );
        }
        return null;
    }

    private void buttonOutcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutcomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOutcomeActionPerformed

    private void buttonIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonIncomeActionPerformed

    private String getSelectedButton() {
        if (buttonIncome.isSelected()) return buttonIncome.getText();

        return buttonOutcome.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTransactionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTransactionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTransactionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTransactionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTransactionView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CategoriesBox;
    private javax.swing.JRadioButton buttonIncome;
    private javax.swing.JRadioButton buttonOutcome;
    private javax.swing.ButtonGroup buttonTypeGroup;
    private javax.swing.JTextField dateInputText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nameInputText;
    private javax.swing.JTextField priceInputText;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
